### ISSUE TITLE
代码for效率问题

### ISSUE THREAD

**Issue by Fu-XDU** [cnzhangxy51/dynamic-thread-pool#1]
[这里](https://github.com/cnzhangxy51/dynamic-thread-pool/blob/0ddf58aa178f48a05fad538218209496ec41d14f/dynamic-thread-pool-core/src/main/java/cn/xyfv/middleware/dynamic/thread/pool/sdk/config/DynamicThreadPoolAutoConfig.java#L100)写的是`refreshers.get(0);`，为什么前面要这么写呢：
```
for (IRefresher refresher : serviceLoader) {
    refreshers.add(refresher);
}
```

直接这么写会不会更高效呢：
```
for (IRefresher refresher : serviceLoader) {
    return refresher;
}
```

**Comment by cnzhangxy51** [comment]
目前的场景下可以这么做，之所以这么写是为了后续的一些开发 : )

**Comment by Fu-XDU** [comment]
这种可预见的异常不应该由try catch捕获，而是通过判断`refreshers.size()==0`来捕获

**Comment by cnzhangxy51** [comment]
no，会报BeanCreationException的
